### PR TITLE
dayatsin/gpu remapping

### PR DESCRIPTION
**Pull request by dayatsin-amd**
Changes to support GPU remapping when restoring on node with different topology
Additional verifications for GPU properties when restoring
Changed dump function to copy BO contents in separate threads to speed-up checkpointing on MGPU nodes

### CODE REVIEW

**Comment by rajbhar** [comment]
shows some minor merge conflicts + test case should ideally be a part of ZDTM test suite, IMO.

**Comment by dayatsin-amd** [comment]
> shows some minor merge conflicts + test case should ideally be a part of ZDTM test suite, IMO.

I am seeing conflicts from the initial push, that was because I initially did a push instead of force-push. I re-did a force-push after. I am not seeing conflicts after the force-push. Let me know if it is still showing merge conflicts on the last force-push for you.

I looked at the ZTDM test suite:
1. I did not want to put the code there as the test coverage there is for functions that are inside the CRIU core application and not plugins
2. Also, putting the code there would mean we would have to duplicate checks once we start adding dependencies for amdgpu plugin.

But the ZTDM test suite does has some nice wrappers, so I will take a look again at integrating it with the ZDTM test suite.

**Comment by rajbhar** [comment]
[AMD Official Use Only]

Hi David, I still see a merge conflict.  If you started criu-dev from criu-new repo and rebased your work on that, ideally we should not see any conflicts on your new PR.

**Comment by dayatsin-amd** [comment]
> [AMD Official Use Only] Hi David, I still see a merge conflict. If you started criu-dev from criu-new repo and rebased your work on that, ideally we should not see any conflicts on your new PR.
Yes, you are right, the conflicts are from latest force push. I started from criu-new criu-dev branch. I will take a look in the afternoon.

**Pull request closed without merging**
